### ISSUE TITLE
Chrome 80 - install.py no longer exists

### ISSUE THREAD

**Issue by grahampugh** [hjuutilainen/adminscripts#17]
The `chrome-enable-autoupdates.py` script has started failing with version 80. It seems that the `install.py` file is no longer provided. Not sure if that's something that can be addressed.

```
install_script = os.path.join(keystone_registration_framework_path(), 'Resources/install.py')
```

**Comment by hjuutilainen** [comment]
Thanks for reporting, it seems that they moved the `ksinstall` tool from Resources to Helpers directory. I've just pushed an update to the script which should find it correctly.
