### ISSUE TITLE
download-logicprox-content downloads numerous duplicates

### ISSUE THREAD

**Issue by jazzace** [hjuutilainen/adminscripts#3]
In investigating why the list generated by `download-logicprox-content.py list` contained 850 items but `download-logicprox-content.py download` downloaded 846 items, I noticed that a number of items were actually duplicates. Using TextWrangler and a captured version of the list, I eliminated the duplicate lines, which reduced it to 357 packages. Some packages were downloaded as many as 9 times. The duplicates all appear to come from the Alchemy Sound Libraries.

**Comment by hjuutilainen** [comment]
The script is now updated and should be smarter about duplicate items. It now first downloads individual packages to "__Downloaded Items" directory and creates hard links to recreate the structure in Logic's UI.

**Comment by clburlison** [comment]
@hjuutilainen The updated script resolves the duplicated content for me. Thanks Hannes!
