### ISSUE TITLE
Could you add a license to your repo?

### ISSUE THREAD

**Issue by homebysix** [hjuutilainen/adminscripts#7]
My organization would like to use and modify some of your scripts, but the absence of a license prevents us from doing so. Could you add one?

Thank you!

**Comment by hjuutilainen** [comment]
Of course, sorry about this! Added a MIT license in f1f7de0146c069bcd40a2be96a7077d8e4ad49a8.

**Comment by homebysix** [comment]
Fantastic, thank you!
